title: bye-bye-code
author: dappaduppa
email: duppadappa@gmail.com
description: This is an attempt to code faster, bye bye to novice code
twitter_username: dappaduppa
github_username:  dappaduppa

# Build settings
markdown: kramdown
theme: minima
